version: '3.8'
services:
  backend:
    build: ./backend
    container_name: mathmodel-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    restart: always
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: mathmodel-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
  redis:
    image: redis:7
    container_name: mathmodel-redis
    ports:
      - "6379:6379"
    restart: always